// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SosDog.Models;

#nullable disable

namespace Dev_PUC_SoSDog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SosDog.Models.Comentario", b =>
                {
                    b.Property<int>("ID_Comentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Comentario"));

                    b.Property<DateTime>("Data_hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Ocorrencia")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Comentario");

                    b.HasIndex("ID_Ocorrencia");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("SosDog.Models.Favorito", b =>
                {
                    b.Property<int>("ID_Favorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Favorito"));

                    b.Property<int>("ID_Ocorrencia")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID_Favorito");

                    b.HasIndex("ID_Ocorrencia");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("SosDog.Models.Ocorrencia", b =>
                {
                    b.Property<int>("ID_Ocorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Ocorrencia"));

                    b.Property<DateTime>("Data_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto_Animal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Ocorrencia");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("SosDog.Models.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_Cadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto_Perfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizacaoAtual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Telefone")
                        .HasColumnType("int");

                    b.HasKey("ID_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SosDog.Models.Comentario", b =>
                {
                    b.HasOne("SosDog.Models.Ocorrencia", "Ocorrencia")
                        .WithMany("Comentarios")
                        .HasForeignKey("ID_Ocorrencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SosDog.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SosDog.Models.Favorito", b =>
                {
                    b.HasOne("SosDog.Models.Ocorrencia", "Ocorrencia")
                        .WithMany("FavoritadosPor")
                        .HasForeignKey("ID_Ocorrencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SosDog.Models.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SosDog.Models.Ocorrencia", b =>
                {
                    b.HasOne("SosDog.Models.Usuario", "Usuario")
                        .WithMany("OcorrenciasRegistradas")
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SosDog.Models.Ocorrencia", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("FavoritadosPor");
                });

            modelBuilder.Entity("SosDog.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Favoritos");

                    b.Navigation("OcorrenciasRegistradas");
                });
#pragma warning restore 612, 618
        }
    }
}
